; PlatformIO Project Configuration File

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_port = COM14
upload_speed = 115200
monitor_port = COM14
monitor_speed = 115200
board_build.f_cpu = 16000000L
build_flags =
    -flto
    -fdata-sections
    -ffunction-sections
    -Wl,--gc-sections
lib_deps =